### ISSUE TITLE
Log HTTP Responses

### ISSUE THREAD

**Issue by EstebanBorai** [infinyon/http-sink-connector#31]
As part of supporting debugging we would like to have HTTP Response Logged

**Comment by ajhunyady** [comment]
Is this something we can enable/disable via CLI?

**Comment by morenol** [comment]
I think that for info level, we should output the http response status code. Also, I think that we should add a info log level for every record read:

https://github.com/infinyon/http-sink-connector/blob/674d331e02b8a9c435e4b2e48ab58d9a9f3c2df7/crates/http-sink/src/main.rs#L19 Maybe we can print there the record size.

**Comment by EstebanBorai** [comment]
With regards to toggling logs on the fly I think we can use this approach from the same crate we use for logging:

https://docs.rs/tracing-subscriber/latest/tracing_subscriber/reload/index.html

We just have to design how the logging is switched from the CLI

**Comment by morenol** [comment]
I think that for that, we should create a mechanism to set environment variables on connectors. Maybe that way we can just set `RUST_LOG` with the value we want in the rust connectors

**Comment by ajhunyady** [comment]
We wouldn't want to add Info level logs for high frequency message, as it will impact performance and it will burry important messages such as errors. Instead we should have a way to add debug, and implement `stats` for counters such as incoming records, outgoing records, and whatever else is relevant for troubleshooting.

**Comment by morenol** [comment]
Even a http servers typically uses an info log for reporting status code of each request, I think that it should not impact performance

**Comment by sehz** [comment]
Log level should be up to the user since it will impact performance and incur additional costs.
